# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jason Fan.
subtitle: Nothing is impossible！
description: '未来与过去无关，未来由现在决定!'
keywords: OI,题解,算法笔记
author: Jason-Fan
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
# url: https://fanxz.gitee.io/
url: https://blog.jasonfan.ml/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# hexo-generator-index -> https://github.com/hexojs/hexo-generator-index
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page



# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: git
  repo: https://github.com/jason-fxz/jason-fxz.github.io
  branch: master
# - type: git
#   repo: https://gitee.com/fanxz/fanxz
#   branch: master


symbols_count_time:
 #文章内是否显示
  symbols: true
  time: true
 # 网页底部是否显示
  total_symbols: true
  total_time: true
  
# 站内搜索
search:
  path: search.xml
  field: post
  content: true
  # template: ./search.xml

# Security
encrypt: # hexo-blog-encrypt
  abstract: 有东西被加密了, 请输入暗号查看.
  message: 暗号？
  tags:
  - {name: XJ, password: XueJunOI666}
  - {name: personal, password: Bits1206}
  theme: xray
  # template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 抱歉, 这个暗号看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# markdown 渲染 hexo-renderer-markdown-it -> https://github.com/hexojs/hexo-renderer-markdown-it
markdown:
  plugins:
    - plugin:
      name: '@neilsustc/markdown-it-katex'
      options:
        strict: false


# hexo-hide-posts
hide_posts:
  ## 隐藏标记名，可以改成其他你喜欢的名字 
  filter: hidden
  ## 指定你想要传递隐藏文章的 generator，比如让所有隐藏文章在存档页面可见
  ## 常见的 generators 有：index, tag, category, archive, sitemap, feed, etc.
  public_generators: [tag]
  ## 为隐藏的文章添加 noindex meta 标签，阻止搜索引擎收录
  noindex: false